name = "GeoScanning"
uuid = "6f076f23-2162-4a79-aecc-299a3176c096"
authors = ["Renato Aranha"]
version = "0.1.0"

[deps]
GeoStatsBase = "323cb8eb-fbf6-51c0-afd0-f8fba70507b2"
NearestNeighbors = "b8a86587-4115-5ab1-83bc-aa920d37bbce"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
